# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80cfdf3c263ab9aaddb1f3943e96a7f95067adbc8929eb3b10d0ae0cd534cc673c135039e2133906b8ce5258b47cbb09c6ec2f5ced768234514007ebbb2151ec

test:
  secret_key_base: d95593b60f0cccb513dea5ccbde75e3af9b524a1d4c6f55088a98db873800a598951a5e1a6c356ee896e2b14ba21faabffad6bf43c14626f44f81af1313eb989

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
